#!/bin/bash
PR=$1
test -z $PR && echo 'needs a PR number' 1>&2 && exit 1

git remote -v | grep github >/dev/null
NOT_GITHUB=$?
if (( $NOT_GITHUB )); then
    REF=pull-requests/$PR/from
else
    REF=pull/$PR/head
    #REF=pull/$PR/merge
fi

git fetch upstream $REF
git checkout FETCH_HEAD
