#!/usr/bin/env python
import importlib
import os
import subprocess
import sys


if __name__ == '__main__':
    name = sys.argv[1]
    print 'Checking for:', name
    module = importlib.import_module(name)
    path = module.__file__
    print '   path:', module.__file__
    real_path = os.path.realpath(module.__file__)
    if path != real_path:
        print '         -> ', os.path.realpath(module.__file__)
    cwd = os.path.dirname(module.__file__)
    # Ignore modules stored in egg files
    if os.path.isdir(cwd):
        try:
            output = subprocess.check_output(['git', 'log', '-1', '--decorate',
                                              '--format=%H %an%+d%+s'], cwd=cwd,
                                             stderr=subprocess.STDOUT)
            first, second, third = output.split('\n', 2)
            print '    git:', first
            print '       ', second
            print '        ', third.strip()
        except subprocess.CalledProcessError:
            pass
    version_names = [name for name in dir(module) if 'version' in name.lower()]
    if version_names:
        print ' module:'
        for name in version_names:
            print '        ', '{}: {}'.format(name, getattr(module, name))
